favicon: null
name: yamis
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5215054
  brandStrength: 0
  rhythmicContrast: 0.4928315
  brandColors:
    - '#2E469C'
    - '#23AA4B'
    - '#E7472F'
    - '#E7AE2D'
    - '#8699DE'
  lightness: 0.5197133
typography_spectrum: 0.4175627
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4301075
analytics:
  twitter: null
  google: null
  facebook: null
