name: yamis
favicon: null
layout_spectrum: 0.17173
typography_spectrum: 0.78141
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b2b9c9'
    - '#838fa5'
    - '#53627f'
    - '#2b2c31'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
