cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 0.1003584
  lightness: 1
  brandColors:
    - '#FFF6F7'
  rhythmicContrast: 0.4928315
typography_spectrum: 0.4175627
layout_spectrum: 0.4301075
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: yamis
