name: yamis
favicon: null
layout_spectrum: 0.83567
typography_spectrum: 0.78141
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3bfcd'
    - '#090c13'
    - '#6184b1'
    - '#850413'
    - '#d7a322'
  brandStrength: 0.0625
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
