name: yamis
favicon: null
layout_spectrum: 0.6048168330453336
typography_spectrum: 0.893423484172672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.481364194303751
  lightness: 0.05407759756781161
  saturation: 0.1434255805797875
  rhythmicContrast: 0.8298602406866848
purpose: []
