name: yamis
favicon: null
layout_spectrum: 0.6048168330453336
typography_spectrum: 0.893423484172672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3bfcd'
    - '#090c13'
    - '#6184b1'
    - '#850413'
    - '#d7a322'
  brandStrength: 0.1875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
