favicon: null
name: yamis
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.7921147
  brandStrength: 0
  rhythmicContrast: 0.7921147
  brandColors:
    - '#ffffff'
    - '#b2b9c9'
    - '#838fa5'
    - '#53627f'
    - '#2b2c31'
  lightness: 0.6738351
typography_spectrum: 0.4175627
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2598566
analytics:
  twitter: null
  google: null
  facebook: null
